random_state: 42

dataset:
  n_samples: 5000
  n_features: 12
  n_informative: 6
  n_redundant: 2
  n_clusters_per_class: 2
  weights: [0.9, 0.1]
  flip_y: 0.01

missing_values:
  p_missing: 0.05

features:
  original_cols:
    - age
    - income
    - loan_amount
    - loan_term
    - credit_history_len
    - num_credit_lines
    - delinquencies
    - utilization
    - employment_years
    - num_open_accounts
    - avg_monthly_balance
    - feature_extra
  target_col: default
  missing_indicator_cols:
    - income
    - employment_years
    - avg_monthly_balance

model:
  test_size: 0.2
  cv_folds: 5
  use_smote: false
  fp_cost: 100.0
  fn_cost: 2500.0
  lgbm_params:
    n_estimators: 150
    max_depth: 4
    learning_rate: 0.05
    num_leaves: 31
    min_child_samples: 20
    subsample: 0.8
    reg_alpha: 0.1
    reg_lambda: 0.1
    class_weight: balanced
    random_state: 42
    verbosity: -1
    force_col_wise: true

geo:
  n_banks: 15
  bounds:
    x: [-50.0, 50.0]
    y: [-50.0, 50.0]
  distance_features:
    - min_bank_distance
    - mean_bank_distance
    - std_bank_distance
  enforce_monotonic: true
  inject_label_signal: true
  signal_quantile: 0.80
  label_signal_strength: 0.25

visualization:
  top_n_features: 10

calibration:
  enabled: true
  method: isotonic
  cv: 3
